require('dotenv').config();

const mongoose = require('mongoose');
const Course = require('../models/Course');

const freeCoursesCatalog = [
  // ─── 1. freeCodeCamp ────────────────────────────────────────────────────────
  {
    title: 'Responsive Web Design Certification',
    provider: 'freeCodeCamp',
    url: 'https://www.freecodecamp.org/learn/2022/responsive-web-design/',
    skills: ['HTML', 'CSS', 'Responsive Design', 'Web Development', 'Flexbox', 'CSS Grid'],
    level: 'Beginner',
    duration: '300 hours (Self-Paced)',
    free: true,
    freeStatus: '100% Free',
    platform: 'freeCodeCamp',
    instructor: 'freeCodeCamp Community & Quincy Larson',
    credits: 4,
    rating: 4.9,
    enrolledCount: 42000,
    bridgesSkills: ['HTML', 'CSS', 'Responsive Design', 'Web Development'],
    accreditation: 'freeCodeCamp Verified Developer Certification',
    badgeColor: 'tech'
  },
  {
    title: 'JavaScript Algorithms and Data Structures',
    provider: 'freeCodeCamp',
    url: 'https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/',
    skills: ['JavaScript', 'ES6', 'Data Structures', 'Algorithms', 'OOP', 'Functional Programming'],
    level: 'Beginner',
    duration: '300 hours (Self-Paced)',
    free: true,
    freeStatus: '100% Free',
    platform: 'freeCodeCamp',
    instructor: 'freeCodeCamp Curriculum Team',
    credits: 5,
    rating: 4.9,
    enrolledCount: 58000,
    bridgesSkills: ['JavaScript', 'Data Structures', 'Algorithms'],
    accreditation: 'freeCodeCamp Verified Certification',
    badgeColor: 'tech'
  },
  {
    title: 'Front End Development Libraries (React & Redux)',
    provider: 'freeCodeCamp',
    url: 'https://www.freecodecamp.org/learn/front-end-development-libraries/',
    skills: ['React.js', 'Redux', 'Bootstrap', 'Sass', 'Frontend', 'REST APIs'],
    level: 'Intermediate',
    duration: '300 hours (Self-Paced)',
    free: true,
    freeStatus: '100% Free',
    platform: 'freeCodeCamp',
    instructor: 'freeCodeCamp Staff',
    credits: 5,
    rating: 4.8,
    enrolledCount: 36000,
    bridgesSkills: ['React.js', 'REST APIs', 'Frontend'],
    accreditation: 'freeCodeCamp Verified Certification',
    badgeColor: 'saffron'
  },
  {
    title: 'Back End Development and APIs',
    provider: 'freeCodeCamp',
    url: 'https://www.freecodecamp.org/learn/back-end-development-and-apis/',
    skills: ['Node.js', 'Express', 'MongoDB', 'REST APIs', 'Backend', 'Git'],
    level: 'Intermediate',
    duration: '300 hours (Self-Paced)',
    free: true,
    freeStatus: '100% Free',
    platform: 'freeCodeCamp',
    instructor: 'freeCodeCamp Staff',
    credits: 5,
    rating: 4.9,
    enrolledCount: 31000,
    bridgesSkills: ['REST APIs', 'Git', 'MongoDB', 'Node.js'],
    accreditation: 'freeCodeCamp Industry Standard Certification',
    badgeColor: 'tech'
  },
  {
    title: 'Relational Database Certification (PostgreSQL & SQL)',
    provider: 'freeCodeCamp',
    url: 'https://www.freecodecamp.org/learn/relational-database/',
    skills: ['SQL', 'PostgreSQL', 'Bash', 'Git', 'Databases', 'Relational DB'],
    level: 'Intermediate',
    duration: '300 hours (Self-Paced)',
    free: true,
    freeStatus: '100% Free',
    platform: 'freeCodeCamp',
    instructor: 'freeCodeCamp Staff',
    credits: 4,
    rating: 4.8,
    enrolledCount: 22000,
    bridgesSkills: ['SQL', 'Git', 'PostgreSQL'],
    accreditation: 'freeCodeCamp Linux & SQL Certification',
    badgeColor: 'neutral'
  },
  {
    title: 'Scientific Computing with Python',
    provider: 'freeCodeCamp',
    url: 'https://www.freecodecamp.org/learn/scientific-computing-with-python/',
    skills: ['Python', 'Data Structures', 'Algorithms', 'Problem Solving'],
    level: 'Beginner',
    duration: '300 hours (Self-Paced)',
    free: true,
    freeStatus: '100% Free',
    platform: 'freeCodeCamp',
    instructor: 'Dr. Charles Severance',
    credits: 4,
    rating: 4.9,
    enrolledCount: 49000,
    bridgesSkills: ['Python', 'Data Structures'],
    accreditation: 'freeCodeCamp Certification',
    badgeColor: 'saffron'
  },
  {
    title: 'Machine Learning with Python',
    provider: 'freeCodeCamp',
    url: 'https://www.freecodecamp.org/learn/machine-learning-with-python/',
    skills: ['Python', 'Machine Learning', 'TensorFlow', 'Neural Networks', 'AI'],
    level: 'Advanced',
    duration: '300 hours (Self-Paced)',
    free: true,
    freeStatus: '100% Free',
    platform: 'freeCodeCamp',
    instructor: 'freeCodeCamp Staff & Tim Ruscica',
    credits: 5,
    rating: 4.8,
    enrolledCount: 28000,
    bridgesSkills: ['Python', 'Machine Learning', 'LLM', 'AI'],
    accreditation: 'freeCodeCamp AI Track Certification',
    badgeColor: 'saffron'
  },

  // ─── 2. Khan Academy ────────────────────────────────────────────────────────
  {
    title: 'Computer Science: Algorithms & Asymptotic Analysis',
    provider: 'Khan Academy',
    url: 'https://www.khanacademy.org/computing/computer-science/algorithms',
    skills: ['Algorithms', 'Data Structures', 'Binary Search', 'Sorting', 'Big-O', 'Recursion'],
    level: 'Beginner',
    duration: '20 hours (Self-Paced)',
    free: true,
    freeStatus: '100% Free',
    platform: 'Khan Academy',
    instructor: 'Prof. Tom Cormen & Devin Balkcom (Dartmouth)',
    credits: 3,
    rating: 4.9,
    enrolledCount: 65000,
    bridgesSkills: ['Algorithms', 'Data Structures'],
    accreditation: 'Khan Academy Mastery Recognized',
    badgeColor: 'tech'
  },
  {
    title: 'Intro to SQL: Querying and Managing Data',
    provider: 'Khan Academy',
    url: 'https://www.khanacademy.org/computing/computer-programming/html-css-more/html-css-intro-to-sql',
    skills: ['SQL', 'Databases', 'Relational Queries', 'Database Design'],
    level: 'Beginner',
    duration: '15 hours (Self-Paced)',
    free: true,
    freeStatus: '100% Free',
    platform: 'Khan Academy',
    instructor: 'Pamela Fox',
    credits: 2,
    rating: 4.8,
    enrolledCount: 52000,
    bridgesSkills: ['SQL'],
    accreditation: 'Khan Academy Coding Certificate',
    badgeColor: 'neutral'
  },
  {
    title: 'Linear Algebra for Machine Learning & Data Science',
    provider: 'Khan Academy',
    url: 'https://www.khanacademy.org/math/linear-algebra',
    skills: ['Linear Algebra', 'Vectors', 'Matrices', 'Dot Product', 'Eigenvectors', 'Machine Learning'],
    level: 'Intermediate',
    duration: '40 hours (Self-Paced)',
    free: true,
    freeStatus: '100% Free',
    platform: 'Khan Academy',
    instructor: 'Sal Khan',
    credits: 4,
    rating: 4.9,
    enrolledCount: 78000,
    bridgesSkills: ['Machine Learning', 'Linear Algebra'],
    accreditation: 'Khan Academy Math Honors',
    badgeColor: 'saffron'
  },

  // ─── 3. MIT OpenCourseWare ──────────────────────────────────────────────────
  {
    title: 'MIT 6.0001: Introduction to Computer Science and Programming in Python',
    provider: 'MIT OpenCourseWare',
    url: 'https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/',
    skills: ['Python', 'Computational Thinking', 'Data Structures', 'Algorithms', 'Testing'],
    level: 'Beginner',
    duration: '9 Weeks',
    free: true,
    freeStatus: '100% Free',
    platform: 'MIT OpenCourseWare',
    instructor: 'Prof. Eric Grimson & Dr. Ana Bell',
    credits: 4,
    rating: 5.0,
    enrolledCount: 94000,
    bridgesSkills: ['Python', 'Data Structures'],
    accreditation: 'Massachusetts Institute of Technology Open Course',
    badgeColor: 'saffron'
  },
  {
    title: 'MIT 6.006: Introduction to Algorithms',
    provider: 'MIT OpenCourseWare',
    url: 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/',
    skills: ['Data Structures', 'Algorithms', 'Dynamic Programming', 'Graph Algorithms', 'Trees', 'Hashing'],
    level: 'Intermediate',
    duration: '14 Weeks',
    free: true,
    freeStatus: '100% Free',
    platform: 'MIT OpenCourseWare',
    instructor: 'Prof. Erik Demaine & Dr. Jason Ku',
    credits: 5,
    rating: 5.0,
    enrolledCount: 88000,
    bridgesSkills: ['Data Structures', 'Algorithms'],
    accreditation: 'MIT EECS Core Course Curriculum',
    badgeColor: 'tech'
  },
  {
    title: 'MIT 6.033: Computer System Engineering & Architecture',
    provider: 'MIT OpenCourseWare',
    url: 'https://ocw.mit.edu/courses/6-033-computer-systems-engineering-spring-2018/',
    skills: ['System Design', 'Distributed Systems', 'Networking', 'Security', 'Operating Systems'],
    level: 'Advanced',
    duration: '12 Weeks',
    free: true,
    freeStatus: '100% Free',
    platform: 'MIT OpenCourseWare',
    instructor: 'Prof. Frans Kaashoek & Dr. Katrina LaCurts',
    credits: 5,
    rating: 4.9,
    enrolledCount: 41000,
    bridgesSkills: ['System Design'],
    accreditation: 'MIT Advanced Computer Systems Credential',
    badgeColor: 'neutral'
  },
  {
    title: 'MIT 6.036: Introduction to Machine Learning',
    provider: 'MIT OpenCourseWare',
    url: 'https://ocw.mit.edu/courses/6-036-introduction-to-machine-learning-fall-2020/',
    skills: ['Python', 'Machine Learning', 'Neural Networks', 'PyTorch', 'Reinforcement Learning', 'LLM'],
    level: 'Advanced',
    duration: '12 Weeks',
    free: true,
    freeStatus: '100% Free',
    platform: 'MIT OpenCourseWare',
    instructor: 'Prof. Leslie Kaelbling & Prof. Tomás Lozano-Pérez',
    credits: 5,
    rating: 4.9,
    enrolledCount: 51000,
    bridgesSkills: ['Python', 'PyTorch', 'LLM', 'Machine Learning'],
    accreditation: 'MIT Machine Learning Program',
    badgeColor: 'saffron'
  },

  // ─── 4. SWAYAM / NPTEL (Government of India) ────────────────────────────────
  {
    title: 'Cloud Computing, Virtualization & Containers (NPTEL)',
    provider: 'SWAYAM',
    url: 'https://swayam.gov.in/courses/public',
    skills: ['Cloud', 'Docker', 'Kubernetes', 'AWS', 'Virtualization', 'Microservices'],
    level: 'Intermediate',
    duration: '8 Weeks',
    free: true,
    freeStatus: '100% Free',
    platform: 'SWAYAM',
    instructor: 'Prof. Soumya Kanti Ghosh (IIT Kharagpur)',
    credits: 4,
    rating: 4.8,
    enrolledCount: 31000,
    bridgesSkills: ['Cloud', 'Docker', 'Kubernetes', 'AWS'],
    accreditation: 'AICTE Approved & NCrF Credit Transfer Recognized',
    badgeColor: 'tech'
  },
  {
    title: 'Programming, Data Structures And Algorithms Using Python',
    provider: 'SWAYAM',
    url: 'https://swayam.gov.in/courses/public',
    skills: ['Python', 'Data Structures', 'Algorithms', 'Sorting', 'Recursion'],
    level: 'Beginner',
    duration: '8 Weeks',
    free: true,
    freeStatus: '100% Free',
    platform: 'SWAYAM',
    instructor: 'Prof. Madhavan Mukund (Chennai Mathematical Institute)',
    credits: 3,
    rating: 4.9,
    enrolledCount: 62000,
    bridgesSkills: ['Python', 'Data Structures', 'Algorithms'],
    accreditation: 'NPTEL · Ministry of Education, Govt of India',
    badgeColor: 'saffron'
  },
  {
    title: 'Modern Database Systems: Relational & Distributed (NPTEL)',
    provider: 'SWAYAM',
    url: 'https://swayam.gov.in/courses/public',
    skills: ['SQL', 'Databases', 'Relational DB', 'Indexing', 'Query Optimization'],
    level: 'Intermediate',
    duration: '8 Weeks',
    free: true,
    freeStatus: '100% Free',
    platform: 'SWAYAM',
    instructor: 'Prof. Partha Pratim Das (IIT Kharagpur)',
    credits: 3,
    rating: 4.7,
    enrolledCount: 29000,
    bridgesSkills: ['SQL'],
    accreditation: 'IIT Kharagpur NPTEL Verified Course',
    badgeColor: 'neutral'
  },
  {
    title: 'Deep Learning with PyTorch & Neural Networks',
    provider: 'SWAYAM',
    url: 'https://swayam.gov.in/courses/public',
    skills: ['PyTorch', 'Deep Learning', 'Neural Networks', 'Python', 'LLM', 'Computer Vision'],
    level: 'Advanced',
    duration: '12 Weeks',
    free: true,
    freeStatus: '100% Free',
    platform: 'SWAYAM',
    instructor: 'Prof. P. K. Biswas (IIT Kharagpur)',
    credits: 4,
    rating: 4.8,
    enrolledCount: 24000,
    bridgesSkills: ['PyTorch', 'LLM', 'Python'],
    accreditation: 'National Programme on Technology Enhanced Learning (NPTEL)',
    badgeColor: 'saffron'
  },
  {
    title: 'Computer Networks and Internet Protocols',
    provider: 'SWAYAM',
    url: 'https://swayam.gov.in/courses/public',
    skills: ['Networking', 'TCP/IP', 'Routing', 'REST APIs', 'Security', 'HTTP'],
    level: 'Intermediate',
    duration: '12 Weeks',
    free: true,
    freeStatus: '100% Free',
    platform: 'SWAYAM',
    instructor: 'Prof. Soumya Kanti Ghosh (IIT Kharagpur)',
    credits: 4,
    rating: 4.8,
    enrolledCount: 38000,
    bridgesSkills: ['REST APIs'],
    accreditation: 'Ministry of Education · Govt of India',
    badgeColor: 'tech'
  },

  // ─── 5. edX (Free Audit Track) ──────────────────────────────────────────────
  {
    title: "CS50's Introduction to Computer Science (Harvard)",
    provider: 'edX',
    url: 'https://www.edx.org/learn/computer-science/harvard-university-cs50-s-introduction-to-computer-science',
    skills: ['C', 'Python', 'SQL', 'HTML', 'CSS', 'JavaScript', 'Data Structures', 'Algorithms'],
    level: 'Beginner',
    duration: '12 Weeks (Self-Paced)',
    free: true,
    freeStatus: '100% Free',
    platform: 'edX',
    instructor: 'Prof. David J. Malan (Harvard University)',
    credits: 5,
    rating: 5.0,
    enrolledCount: 150000,
    bridgesSkills: ['Python', 'SQL', 'Data Structures', 'Algorithms'],
    accreditation: 'Harvard University / edX Free Audit Access',
    badgeColor: 'tech'
  },
  {
    title: "CS50's Web Programming with Python and JavaScript",
    provider: 'edX',
    url: 'https://www.edx.org/learn/web-development/harvard-university-cs50-s-web-programming-with-python-and-javascript',
    skills: ['Python', 'JavaScript', 'Django', 'React.js', 'SQL', 'Git', 'REST APIs', 'Next.js / SSR'],
    level: 'Intermediate',
    duration: '12 Weeks',
    free: true,
    freeStatus: '100% Free',
    platform: 'edX',
    instructor: 'Brian Yu & David J. Malan (Harvard)',
    credits: 5,
    rating: 4.9,
    enrolledCount: 92000,
    bridgesSkills: ['React.js', 'Python', 'Git', 'SQL', 'REST APIs', 'Next.js / SSR'],
    accreditation: 'HarvardX Free Course Curriculum',
    badgeColor: 'saffron'
  },
  {
    title: 'Introduction to Kubernetes and Cloud Native Architecture',
    provider: 'edX',
    url: 'https://www.edx.org/learn/kubernetes/the-linux-foundation-introduction-to-kubernetes',
    skills: ['Kubernetes', 'Docker', 'Containers', 'Cloud', 'DevOps', 'Microservices'],
    level: 'Intermediate',
    duration: '14 Weeks (Self-Paced)',
    free: true,
    freeStatus: '100% Free',
    platform: 'edX',
    instructor: 'The Linux Foundation',
    credits: 4,
    rating: 4.8,
    enrolledCount: 47000,
    bridgesSkills: ['Kubernetes', 'Docker', 'AWS'],
    accreditation: 'Cloud Native Computing Foundation (CNCF) / Linux Foundation',
    badgeColor: 'tech'
  },
  {
    title: 'Introduction to Linux & Shell Scripting',
    provider: 'edX',
    url: 'https://www.edx.org/learn/linux/the-linux-foundation-introduction-to-linux',
    skills: ['Git', 'Bash', 'Command Line', 'DevOps', 'System Administration'],
    level: 'Beginner',
    duration: '14 Weeks',
    free: true,
    freeStatus: '100% Free',
    platform: 'edX',
    instructor: 'Jerry Cooperstein (The Linux Foundation)',
    credits: 3,
    rating: 4.8,
    enrolledCount: 73000,
    bridgesSkills: ['Git'],
    accreditation: 'The Linux Foundation Official Training',
    badgeColor: 'neutral'
  },

  // ─── 6. YouTube (Official High-Quality Video Courses) ────────────────────────
  {
    title: 'Full React 18 & Next.js Masterclass: Zero to Hero',
    provider: 'YouTube',
    url: 'https://www.youtube.com/watch?v=bMknfKXIFA8',
    skills: ['React.js', 'Next.js / SSR', 'TypeScript', 'REST APIs', 'Frontend'],
    level: 'Intermediate',
    duration: '12 Hours (Full Course)',
    free: true,
    freeStatus: '100% Free',
    platform: 'YouTube',
    instructor: 'freeCodeCamp.org & Bob Ziroll',
    credits: 3,
    rating: 4.9,
    enrolledCount: 110000,
    bridgesSkills: ['React.js', 'Next.js / SSR', 'TypeScript', 'REST APIs'],
    accreditation: 'Verified Open Educational Resource',
    badgeColor: 'saffron'
  },
  {
    title: 'Docker & Kubernetes Full Course for Beginners',
    provider: 'YouTube',
    url: 'https://www.youtube.com/watch?v=fqMOX6JJhGo',
    skills: ['Docker', 'Kubernetes', 'Containers', 'DevOps', 'AWS', 'Microservices'],
    level: 'Beginner',
    duration: '6 Hours (Full Course)',
    free: true,
    freeStatus: '100% Free',
    platform: 'YouTube',
    instructor: 'TechWorld with Nana / freeCodeCamp',
    credits: 3,
    rating: 4.9,
    enrolledCount: 125000,
    bridgesSkills: ['Docker', 'Kubernetes', 'AWS'],
    accreditation: 'Cloud Native Open Course',
    badgeColor: 'tech'
  },
  {
    title: 'System Design Interview – Step by Step Architecture Guide',
    provider: 'YouTube',
    url: 'https://www.youtube.com/watch?v=m8Icp_Cid5o',
    skills: ['System Design', 'Distributed Systems', 'Load Balancing', 'Caching', 'Microservices', 'REST APIs'],
    level: 'Advanced',
    duration: '8 Hours',
    free: true,
    freeStatus: '100% Free',
    platform: 'YouTube',
    instructor: 'freeCodeCamp.org',
    credits: 4,
    rating: 4.9,
    enrolledCount: 95000,
    bridgesSkills: ['System Design', 'REST APIs'],
    accreditation: 'Enterprise Software Engineering Curriculum',
    badgeColor: 'neutral'
  },
  {
    title: 'Git & GitHub Crash Course for Developers',
    provider: 'YouTube',
    url: 'https://www.youtube.com/watch?v=RGOj5yH7evk',
    skills: ['Git', 'GitHub', 'Version Control', 'Branching', 'CI/CD'],
    level: 'Beginner',
    duration: '2 Hours',
    free: true,
    freeStatus: '100% Free',
    platform: 'YouTube',
    instructor: 'freeCodeCamp.org',
    credits: 1,
    rating: 4.9,
    enrolledCount: 89000,
    bridgesSkills: ['Git'],
    accreditation: 'Open Source Community Guide',
    badgeColor: 'tech'
  },
  {
    title: 'AWS Certified Cloud Practitioner - Full Certification Course',
    provider: 'YouTube',
    url: 'https://www.youtube.com/watch?v=SOTamWNgDKc',
    skills: ['AWS', 'Cloud', 'EC2', 'S3', 'IAM', 'Security', 'DevOps'],
    level: 'Beginner',
    duration: '14 Hours',
    free: true,
    freeStatus: '100% Free',
    platform: 'YouTube',
    instructor: 'Andrew Brown (ExamPro) / freeCodeCamp',
    credits: 4,
    rating: 4.9,
    enrolledCount: 140000,
    bridgesSkills: ['AWS'],
    accreditation: 'AWS Certification Curriculum Aligned',
    badgeColor: 'saffron'
  },
  {
    title: 'PyTorch for Deep Learning & Machine Learning Bootcamp',
    provider: 'YouTube',
    url: 'https://www.youtube.com/watch?v=V_xro1bcAuA',
    skills: ['PyTorch', 'Python', 'Deep Learning', 'Neural Networks', 'LLM', 'AI'],
    level: 'Intermediate',
    duration: '26 Hours',
    free: true,
    freeStatus: '100% Free',
    platform: 'YouTube',
    instructor: 'Daniel Bourke / freeCodeCamp',
    credits: 5,
    rating: 5.0,
    enrolledCount: 84000,
    bridgesSkills: ['PyTorch', 'Python', 'LLM'],
    accreditation: 'Deep Learning Open Certification',
    badgeColor: 'saffron'
  },
  {
    title: 'TypeScript Full Course for Beginners to Pro',
    provider: 'YouTube',
    url: 'https://www.youtube.com/watch?v=gieEQFIfgYc',
    skills: ['TypeScript', 'JavaScript', 'Generics', 'OOP', 'React.js'],
    level: 'Intermediate',
    duration: '5 Hours',
    free: true,
    freeStatus: '100% Free',
    platform: 'YouTube',
    instructor: 'Dave Gray',
    credits: 2,
    rating: 4.9,
    enrolledCount: 67000,
    bridgesSkills: ['TypeScript', 'React.js'],
    accreditation: 'Verified Developer Resource',
    badgeColor: 'tech'
  },
  {
    title: 'Next.js 14 Complete In-Depth Tutorial',
    provider: 'YouTube',
    url: 'https://www.youtube.com/watch?v=wm5gMKuwSYk',
    skills: ['Next.js / SSR', 'React.js', 'Server Components', 'REST APIs', 'TypeScript'],
    level: 'Intermediate',
    duration: '5 Hours',
    free: true,
    freeStatus: '100% Free',
    platform: 'YouTube',
    instructor: 'freeCodeCamp.org',
    credits: 3,
    rating: 4.9,
    enrolledCount: 78000,
    bridgesSkills: ['Next.js / SSR', 'React.js', 'TypeScript'],
    accreditation: 'Web Engineering Tutorial',
    badgeColor: 'saffron'
  }
];

async function seedCourses() {
  const uri = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/skillsetu';
  console.log('Connecting to MongoDB:', uri.replace(/\/\/([^:]+):([^@]+)@/, '//***:***@'));

  await mongoose.connect(uri);
  console.log('MongoDB connected successfully.');

  const existing = await Course.countDocuments();
  console.log(`Current courses in DB: ${existing}`);

  await Course.deleteMany({});
  console.log('Cleared existing courses.');

  const inserted = await Course.insertMany(freeCoursesCatalog);
  console.log(`Successfully seeded ${inserted.length} 100% free courses from freeCodeCamp, Khan Academy, MIT OpenCourseWare, SWAYAM, edX, and YouTube!`);

  await mongoose.disconnect();
  console.log('Database connection closed.');
}

if (require.main === module) {
  seedCourses().catch((err) => {
    console.error('Failed to seed free courses:', err);
    process.exit(1);
  });
}

module.exports = { freeCoursesCatalog, seedCourses };
